[package]
name = "smart-id-rs"
description = "Smart-ID client library for Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
strum = { version = "0.24", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
x509-parser = "0.15"
openssl = "0.10"
sha2 = "0.10"
rand = "0.8"
hex = "0.4"
thiserror = "1"
regex = "1"
anyhow = "1"