#[cfg(test)]
mod tests {
    use crate::smart_id::{SmartIdClient, SmartIdError};
    // use std::result::Result; // Removed unused import
    use crate::smart_id::models::{
        AuthenticationHash, CertificateLevel, Interaction, SemanticsIdentifier, // Removed HashType
        SessionSignature, SessionCertificate, AuthenticationSessionResponse,
        SessionStatus, SessionStatusCode, SessionResult, SessionEndResultCode,
        SmartIdErrorResponse
    };
    use crate::smart_id::models::SemanticsIdentifierTypes;

    // Wiremock imports
    use wiremock::{MockServer, Mock, ResponseTemplate, matchers::{method, path, path_regex}};

    // Helper function to create a dummy AuthenticationHash for client initialization
    fn dummy_auth_hash() -> AuthenticationHash {
        AuthenticationHash::new("dummy_data_to_sign_for_smart_id_client_init".to_string())
    }

    #[test]
    fn test_client_initialization_valid() {
        // In smart_id/mod.rs, SmartIdClient::new takes 5 arguments.
        // The previous successful test for smart_id used this.
        let _client = SmartIdClient::new(
            "https://example.com".to_string(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(), // This provides the AuthenticationHash
            None, // Option<&'a Certificate> for ssl_pinned_public_keys
        );
        // No panic is the assertion for this simple new()
    }

    #[test]
    fn test_create_auth_session_request_valid() {
        let client = SmartIdClient::new(
            "https://example.com".to_string(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );
        // Create a specific AuthenticationHash for the request itself
        let auth_hash_for_request = AuthenticationHash::new("data for specific request".to_string()); // Removed mut
        // Manually override hash and hash_type for predictable testing,
        // assuming these fields were made public or a method exists to set them for testing.
        // Based on models.rs for smart_id, these fields are private.
        // The constructor AuthenticationHash::new itself calculates the hash and sets type.
        // So we rely on its output.
        // auth_hash_for_request.hash = "test_hash_value".to_string(); // Cannot do this if private
        // auth_hash_for_request.hash_type = HashType::Sha256; // Cannot do this if private
        // The test will use the hash & type generated by AuthenticationHash::new()

        let request = client.create_auth_session_request(
            auth_hash_for_request.clone(),
            Some("test_nonce".to_string()),
            CertificateLevel::Qualified,
            vec![Interaction::of_type_display_text_and_pin("test_display_text".to_string())],
            Some("test_network_interface".to_string()),
        );

        assert_eq!(request.relying_party_uuid, "test_relying_party_uuid");
        assert_eq!(request.relying_party_name, "test_relying_party_name");
        assert_eq!(request.hash_type, auth_hash_for_request.get_hash_type());
        assert_eq!(request.hash, auth_hash_for_request.get_hash());
        assert_eq!(request.nonce, Some("test_nonce".to_string()));
        assert_eq!(request.certificate_level, CertificateLevel::Qualified);
        assert_eq!(request.allowed_interactions_order.len(), 1);
        assert_eq!(request.network_interface, Some("test_network_interface".to_string()));
    }

    #[tokio::test]
    async fn test_authenticate_with_document_number_success() {
        let server = MockServer::start().await;
        let host_url = server.uri();

        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );

        let mock_response_body = AuthenticationSessionResponse {
            session_id: "test_session_id".to_string(),
        };

        Mock::given(method("POST"))
            .and(path("/authentication/document/PNOEE-30303030303-Z1B2-Q"))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&mock_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;

        let result = client.authenticate_with_document_number(
            "PNOEE-30303030303-Z1B2-Q".to_string(),
            None, // nonce
            CertificateLevel::Qualified,
            vec![Interaction::of_type_display_text_and_pin("test".to_string())],
            None // network_interface
        ).await;

        assert!(result.is_ok());
        assert_eq!(result.unwrap().session_id, "test_session_id");
    }

    #[tokio::test]
    async fn test_authenticate_with_document_number_error() {
        let server = MockServer::start().await;
        let host_url = server.uri();

        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );

        let error_response_body = SmartIdErrorResponse { // This is from smart_id::models
            r#type: "/errors/generic-error".to_string(), // Example type
            title: "Bad Request".to_string(), // Example title
            status: 400,
            detail: "Invalid document number".to_string(),
            instance: Some("error-instance-doc-400".to_string()),
            properties: None,
            code: 400,
            message: "Invalid document number".to_string(),
        };
        Mock::given(method("POST"))
            .and(path("/authentication/document/PNOEE-30303030303-Z1B2-Q"))
            .respond_with(ResponseTemplate::new(400)
                .set_body_json(&error_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;

        let result = client.authenticate_with_document_number(
            "PNOEE-30303030303-Z1B2-Q".to_string(),
            None,
            CertificateLevel::Qualified,
            vec![Interaction::of_type_display_text_and_pin("test".to_string())],
            None
        ).await;
        assert!(result.is_err());
        // The error mapping in SmartIdClient for 400 is TechnicalError(message_from_response_body)
        if let SmartIdError::TechnicalError(msg) = result.unwrap_err() {
            assert_eq!(msg, "Invalid document number");
        } else {
            panic!("Expected SmartIdError::TechnicalError");
        }
    }

    #[tokio::test]
    async fn test_authenticate_with_semantics_identifier_success() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );
        let mock_response_body = AuthenticationSessionResponse {
            session_id: "test_session_id_semantics".to_string(),
        };
        let semantics_identifier = SemanticsIdentifier::builder()
            .with_semantics_identifier_type(SemanticsIdentifierTypes::PAS.to_string())
            .with_country_code("EE".to_string())
            .with_identifier("PNOEE-30303030303-Z1B2-Q".to_string())
            .build()
            .unwrap();

        let auth_hash_for_request = AuthenticationHash::new("request_specific_data_for_semantics".to_string());

        Mock::given(method("POST"))
            .and(path_regex(format!("/authentication/etsi/{}", semantics_identifier.as_string())))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&mock_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;

        let result = client.authenticate_with_semantics_identifier(
            &semantics_identifier,
            auth_hash_for_request, // Pass the specific hash for this request
            None,
            CertificateLevel::Qualified,
            vec![Interaction::of_type_display_text_and_pin("test".to_string())],
            None
        ).await;
        assert!(result.is_ok());
        assert_eq!(result.unwrap().session_id, "test_session_id_semantics");
    }

    #[tokio::test]
    async fn test_authenticate_with_semantics_identifier_error() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );
        let semantics_identifier = SemanticsIdentifier::builder()
            .with_semantics_identifier_type(SemanticsIdentifierTypes::PAS.to_string())
            .with_country_code("EE".to_string())
            .with_identifier("PNOEE-30303030303-Z1B2-Q".to_string())
            .build()
            .unwrap();
        // For 401, SmartIdClient maps to SmartIdError::SmartIdUnauthorized directly
        Mock::given(method("POST"))
            .and(path_regex(format!("/authentication/etsi/{}", semantics_identifier.as_string())))
            .respond_with(ResponseTemplate::new(401)) // No body needed for this mapping
            .mount(&server)
            .await;

        let auth_hash_for_request = AuthenticationHash::new("request_specific_data_for_semantics_error".to_string());
        let result = client.authenticate_with_semantics_identifier(
            &semantics_identifier,
            auth_hash_for_request,
            None,
            CertificateLevel::Qualified,
            vec![Interaction::of_type_display_text_and_pin("test".to_string())],
            None
        ).await;
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::SmartIdUnauthorized));
    }

    #[tokio::test]
    async fn test_get_session_status_running() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );
        let mock_response_body = SessionStatus {
            state: SessionStatusCode::RUNNING,
            result: None,
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let session_id = "test_running_session_id";
        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&mock_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;
        let result = client.get_session_status(session_id.to_string()).await;
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::SessionInProgress));
    }

    #[tokio::test]
    async fn test_get_session_status_ok() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );

        let mock_response_body = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Ok,
                document_number: Some("PNOEE-12345678901-OK".to_string()),
            }),
            signature: Some(SessionSignature {
                value: Some("test_signature".to_string()),
                algorithm: Some("ES256".to_string()),
            }),
            cert: Some(SessionCertificate {
                value: "test_certificate".to_string(),
                certificate_level: "QUALIFIED".to_string(),
            }),
            interaction_flow_used: None,
            ignored_properties: None,
        };

        let session_id = "test_ok_session_id";

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&mock_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;

        let result = client.get_session_status(session_id.to_string()).await;
        assert!(result.is_ok());
        let status = result.unwrap();
        assert_eq!(status.state, SessionStatusCode::COMPLETE);
        assert_eq!(status.result.unwrap().end_result, SessionEndResultCode::Ok);
        assert!(status.signature.is_some());
        assert!(status.cert.is_some());
    }

    #[tokio::test]
    async fn test_get_session_status_timeout() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );

        let mock_response_body = SessionStatus {
            state: SessionStatusCode::COMPLETE, // API indicates COMPLETE for final states
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Timeout,
                document_number: Some("PNOEE-TIMEOUT".to_string()),
            }),
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };

        let session_id = "test_timeout_session_id";

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&mock_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;

        let result = client.get_session_status(session_id.to_string()).await;
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::SessionTimeoutException));
    }

    #[tokio::test]
    async fn test_get_session_status_document_unusable() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );

        let mock_response_body = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::DocumentUnusable,
                document_number: Some("PNOEE-UNUSABLE".to_string()),
            }),
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };

        let session_id = "test_unusable_session_id";

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&mock_response_body)
                .insert_header("content-type", "application/json"))
            .mount(&server)
            .await;

        let result = client.get_session_status(session_id.to_string()).await;
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::DocumentUnusableException));
    }

    #[tokio::test]
    async fn test_poll_final_session_status_success() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );
        let session_id = "test_poll_success_session_id";
        let running_response = SessionStatus {
            state: SessionStatusCode::RUNNING,
            result: None,
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let ok_response = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Ok,
                document_number: Some("PNOEE-POLL-OK".to_string()),
            }),
            signature: Some(SessionSignature {
                value: Some("test_signature_poll".to_string()),
                algorithm: Some("ES256".to_string()),
            }),
            cert: Some(SessionCertificate {
                value: "test_certificate_poll".to_string(),
                certificate_level: "QUALIFIED".to_string(),
            }),
            interaction_flow_used: None,
            ignored_properties: None,
        };

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200).set_body_json(&running_response))
            .expect(1)
            .mount(&server)
            .await;

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200).set_body_json(&ok_response))
            .expect(1)
            .mount(&server)
            .await;

        let result = client.poll_final_session_status(session_id.to_string()).await;
        assert!(result.is_ok());
        let status = result.unwrap();
        assert_eq!(status.state, SessionStatusCode::COMPLETE);
        assert_eq!(status.result.unwrap().end_result, SessionEndResultCode::Ok);
        assert!(status.signature.is_some());
        assert!(status.cert.is_some());
    }

    #[tokio::test]
    async fn test_poll_final_session_status_timeout() {
        let server = MockServer::start().await;
        let host_url = server.uri();
        let client = SmartIdClient::new(
            host_url.clone(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        );
        let session_id = "test_poll_timeout_session_id";
        let running_response = SessionStatus {
            state: SessionStatusCode::RUNNING,
            result: None,
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let timeout_response = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Timeout,
                document_number: Some("PNOEE-POLL-TIMEOUT".to_string()),
            }),
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&running_response))
            .expect(1)
            .mount(&server)
            .await;

        Mock::given(method("GET"))
            .and(path(format!("/session/{}", session_id)))
            .respond_with(ResponseTemplate::new(200)
                .set_body_json(&timeout_response))
            .expect(1)
            .mount(&server)
            .await;

        let result = client.poll_final_session_status(session_id.to_string()).await;
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::SessionTimeoutException));
    }

    // Helper function to create a SmartIdClient for validation tests (non-HTTP)
    fn create_client_for_validation() -> SmartIdClient<'static> {
        SmartIdClient::new(
            "https://unused.com".to_string(),
            "test_relying_party_uuid".to_string(),
            "test_relying_party_name".to_string(),
            dummy_auth_hash(),
            None,
        )
    }

    #[test]
    fn test_validate_session_status_ok() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Ok,
                document_number: Some("doc".to_string()),
            }),
            signature: Some(SessionSignature { value: Some("sig".to_string()), algorithm: Some("algo".to_string()) }),
            cert: Some(SessionCertificate { value: "cert".to_string(), certificate_level: "QUALIFIED".to_string() }),
            interaction_flow_used: None,
            ignored_properties: None,
        };
        assert!(client.validate_session_status(&status).is_ok());
    }

    #[test]
    fn test_validate_session_status_missing_signature() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Ok,
                document_number: Some("doc".to_string()),
            }),
            signature: None,
            cert: Some(SessionCertificate { value: "cert".to_string(), certificate_level: "QUALIFIED".to_string() }),
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let result = client.validate_session_status(&status);
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::TechnicalError(_)));
    }

    #[test]
    fn test_validate_session_status_missing_certificate() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Ok,
                document_number: Some("doc".to_string()),
            }),
            signature: Some(SessionSignature { value: Some("sig".to_string()), algorithm: Some("algo".to_string()) }),
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let result = client.validate_session_status(&status);
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::TechnicalError(_)));
    }

    #[test]
    fn test_validate_session_status_result_running() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::RUNNING,
            result: None,
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let result = client.validate_session_status_result(status);
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::SessionInProgress));
    }

    #[test]
    fn test_validate_session_status_result_missing_result_field() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: None,
            signature: None,
            cert: None,
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let result = client.validate_session_status_result(status);
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), SmartIdError::SessionStatusMissingResult));
    }

    #[test]
    fn test_validate_session_status_result_ok() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult {
                end_result: SessionEndResultCode::Ok,
                document_number: Some("doc".to_string()),
            }),
            signature: Some(SessionSignature { value: Some("sig".to_string()), algorithm: Some("algo".to_string()) }),
            cert: Some(SessionCertificate { value: "cert".to_string(), certificate_level: "QUALIFIED".to_string() }),
            interaction_flow_used: None,
            ignored_properties: None,
        };
        let result = client.validate_session_status_result(status);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_session_status_result_user_refused() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::UserRefused, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserRefusedException));
    }

    #[test]
    fn test_validate_session_status_result_timeout() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::Timeout, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::SessionTimeoutException));
    }

    #[test]
    fn test_validate_session_status_result_document_unusable() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::DocumentUnusable, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::DocumentUnusableException));
    }

     #[test]
    fn test_validate_session_status_result_required_interaction_not_supported() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::RequiredInteractionNotSupportedByApp, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::RequiredInteractionNotSupportedByAppException));
    }

    #[test]
    fn test_validate_session_status_result_user_refused_display_text_and_pin() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::UserRefusedDisplayTextAndPIN, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserRefusedDisplayTextAndPinException));
    }

    #[test]
    fn test_validate_session_status_result_user_refused_vc_choice() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::UserRefusedVCChoice, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserRefusedVcChoiceException));
    }

    #[test]
    fn test_validate_session_status_result_user_refused_confirmation_message() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::UserRefusedConfirmationMessage, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserRefusedConfirmationMessageException));
    }

    #[test]
    fn test_validate_session_status_result_user_refused_confirmation_message_with_vc_choice() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::UserRefusedConfirmationMessageWithVCChoice, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserRefusedConfirmationMessageWithVcChoiceException));
    }

    #[test]
    fn test_validate_session_status_result_user_refused_cert_choice() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::UserRefusedCertChoice, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserRefusedCertChoiceException));
    }

    #[test]
    fn test_validate_session_status_result_wrong_vc() {
        let client = create_client_for_validation();
        let status = SessionStatus {
            state: SessionStatusCode::COMPLETE,
            result: Some(SessionResult { end_result: SessionEndResultCode::WrongVC, document_number: Some("doc".to_string()) }),
            signature: None, cert: None, interaction_flow_used: None, ignored_properties: None,
        };
        assert!(matches!(client.validate_session_status_result(status).unwrap_err(), SmartIdError::UserSelectedWrongVerificationCodeException));
    }
}
